### ISSUE TITLE
InfluxDB Connector Issue

### ISSUE THREAD

**Issue by pedrocarreiro** [bonitoo-io/influxdb-connector#29]
I am not able to connect my Docker container with Looker Studio. I enter my data, with the URL being "http://192.168.1.11:8086", and it says that it is not possible to make the connection.
this is the error that is presented to me when i try to connect.
![image](https://github.com/user-attachments/assets/c24e98ef-d34a-43a0-8c6c-60f096ec58f0)

**Comment by bednar** [comment]
If you're explaining to @pedrocarreiro why their connector is unable to connect to a local database and suggesting a solution, here's how you could phrase your response:

---

Hi @pedrocarreiro,

Thank you for reaching out. Based on your description, it seems that the issue with the connector's inability to connect may stem from its current setup attempting to access an InfluxDB instance hosted locally. Since the connector operates from Google Servers, it cannot access databases that are hosted on private or local networks due to network restrictions.

To resolve this issue, you will need to host your InfluxDB on a server with a public IP address, ensuring that it is accessible from the internet. This setup allows the connector operating from Google Servers to establish a successful connection.

Please ensure that your InfluxDB server is properly secured and configured to accept connections from the Google Server IP ranges if you decide to expose it to the internet. Additionally, consider implementing appropriate security measures such as firewalls, encrypted connections, and strong authentication to protect your data.

Best Regards

**Comment by bednar** [comment]
Hi @pedrocarreiro,

Thank you for reaching out. Based on your description, it seems that the issue with the connector's inability to connect may stem from its current setup attempting to access an InfluxDB instance hosted locally. Since the connector operates from Google Servers, it cannot access databases that are hosted on private or local networks due to network restrictions.

To resolve this issue, you will need to host your InfluxDB on a server with a public IP address, ensuring that it is accessible from the internet. This setup allows the connector operating from Google Servers to establish a successful connection.

Please ensure that your InfluxDB server is properly secured and configured to accept connections from the Google Server IP ranges if you decide to expose it to the internet. Additionally, consider implementing appropriate security measures such as firewalls, encrypted connections, and strong authentication to protect your data.

Best Regards
